USE [master]
GO
/****** Object:  Database [PruebaNetCore]    Script Date: 4/10/2023 13:55:53 ******/
CREATE DATABASE [PruebaNetCore]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'PruebaNetCore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PruebaNetCore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'PruebaNetCore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\PruebaNetCore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
-- WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [PruebaNetCore] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaNetCore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PruebaNetCore] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PruebaNetCore] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PruebaNetCore] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PruebaNetCore] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PruebaNetCore] SET ARITHABORT OFF 
GO
ALTER DATABASE [PruebaNetCore] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PruebaNetCore] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PruebaNetCore] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PruebaNetCore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PruebaNetCore] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PruebaNetCore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PruebaNetCore] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PruebaNetCore] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PruebaNetCore] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PruebaNetCore] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PruebaNetCore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PruebaNetCore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PruebaNetCore] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PruebaNetCore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PruebaNetCore] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PruebaNetCore] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [PruebaNetCore] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PruebaNetCore] SET RECOVERY FULL 
GO
ALTER DATABASE [PruebaNetCore] SET  MULTI_USER 
GO
ALTER DATABASE [PruebaNetCore] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PruebaNetCore] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PruebaNetCore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PruebaNetCore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PruebaNetCore] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PruebaNetCore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PruebaNetCore', N'ON'
GO
ALTER DATABASE [PruebaNetCore] SET QUERY_STORE = ON
GO
ALTER DATABASE [PruebaNetCore] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [PruebaNetCore]
GO
--/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 4/10/2023 13:55:54 ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO
--CREATE TABLE [dbo].[__EFMigrationsHistory](
--	[MigrationId] [nvarchar](150) NOT NULL,
--	[ProductVersion] [nvarchar](32) NOT NULL,
-- CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
--(
--	[MigrationId] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
--) ON [PRIMARY]
--GO
/****** Object:  Table [dbo].[Cuentas]    Script Date: 4/10/2023 13:55:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cuentas](
	[NumeroCuenta] [int] NOT NULL,
	[TipoCuenta] [nvarchar](20) NOT NULL,
	[SaldoInicial] [decimal](18, 2) NOT NULL,
	[Estado] [bit] NOT NULL,
	[ClienteId] [int] NOT NULL,
 CONSTRAINT [PK_Cuentas] PRIMARY KEY CLUSTERED 
(
	[NumeroCuenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movimientos]    Script Date: 4/10/2023 13:55:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movimientos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [datetime2](7) NOT NULL,
	[TipoMovimiento] [nvarchar](20) NOT NULL,
	[Valor] [decimal](18, 2) NOT NULL,
	[Saldo] [decimal](18, 2) NOT NULL,
	[CuentaId] [int] NOT NULL,
 CONSTRAINT [PK_Movimientos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Personas]    Script Date: 4/10/2023 13:55:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](150) NOT NULL,
	[Genero] [nvarchar](1) NOT NULL,
	[Edad] [int] NOT NULL,
	[Direccion] [nvarchar](300) NOT NULL,
	[Telefono] [nvarchar](10) NOT NULL,
	[Discriminator] [nvarchar](max) NOT NULL,
	[Contraseña] [nvarchar](16) NULL,
	[Estado] [bit] NULL,
 CONSTRAINT [PK_Personas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Cuentas_ClienteId]    Script Date: 4/10/2023 13:55:54 ******/
CREATE NONCLUSTERED INDEX [IX_Cuentas_ClienteId] ON [dbo].[Cuentas]
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Movimientos_CuentaId]    Script Date: 4/10/2023 13:55:54 ******/
CREATE NONCLUSTERED INDEX [IX_Movimientos_CuentaId] ON [dbo].[Movimientos]
(
	[CuentaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Cuentas]  WITH CHECK ADD  CONSTRAINT [FK_Cuentas_Personas_ClienteId] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Personas] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Cuentas] CHECK CONSTRAINT [FK_Cuentas_Personas_ClienteId]
GO
ALTER TABLE [dbo].[Movimientos]  WITH CHECK ADD  CONSTRAINT [FK_Movimientos_Cuentas_CuentaId] FOREIGN KEY([CuentaId])
REFERENCES [dbo].[Cuentas] ([NumeroCuenta])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Movimientos] CHECK CONSTRAINT [FK_Movimientos_Cuentas_CuentaId]
GO
USE [master]
GO
ALTER DATABASE [PruebaNetCore] SET  READ_WRITE 
GO
